package GUI;

public enum State {
    WALKINGTOGATE, DOINGEMOTES, HANDLINGDIALOGUES, WALKINGTORUBYRINGS, PICKINGUPRUBY, HOPPINGWORLD, WALKINGTOGATEAREA, 
    DOINGEMOTESATGATE, WALKINGTOBANK, BANKING, DEFAULT
}
